name: "3rd-party"

on:
  pull_request:

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v3
        # Refer: https://github.com/actions/dependency-review-action
        with:
          fail-on-severity: low
          # Action will fail if dependencies don't match the list
          #allow-licenses: Apache-2.0, MIT
          #deny-licenses: GPL-3.0, AGPL-1.0, AGPL-3.0, LGPL-2.0, CC-BY-3.0
